// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HotelManager.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TblCustomer
    {
        /// <summary>
        /// Initializes a new instance of the TblCustomer class.
        /// </summary>
        public TblCustomer() { }

        /// <summary>
        /// Initializes a new instance of the TblCustomer class.
        /// </summary>
        public TblCustomer(string cusName, string cusAddress, string cusGender, string idCard = default(string), string cusPhone = default(string), IList<TblRoombook> tblRoombook = default(IList<TblRoombook>), IList<TblServicesuse> tblServicesuse = default(IList<TblServicesuse>))
        {
            IdCard = idCard;
            CusName = cusName;
            CusAddress = cusAddress;
            CusGender = cusGender;
            CusPhone = cusPhone;
            TblRoombook = tblRoombook;
            TblServicesuse = tblServicesuse;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idCard")]
        public string IdCard { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cusName")]
        public string CusName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cusAddress")]
        public string CusAddress { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cusGender")]
        public string CusGender { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "cusPhone")]
        public string CusPhone { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tbl_roombook")]
        public IList<TblRoombook> TblRoombook { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tbl_servicesuse")]
        public IList<TblServicesuse> TblServicesuse { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (CusName == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "CusName");
            }
            if (CusAddress == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "CusAddress");
            }
            if (CusGender == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "CusGender");
            }
            if (this.IdCard != null)
            {
                if (this.IdCard.Length > 12)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "IdCard", 12);
                }
                if (this.IdCard.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "IdCard", 0);
                }
            }
            if (this.CusName != null)
            {
                if (this.CusName.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CusName", 255);
                }
                if (this.CusName.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CusName", 0);
                }
            }
            if (this.CusAddress != null)
            {
                if (this.CusAddress.Length > 255)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CusAddress", 255);
                }
                if (this.CusAddress.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CusAddress", 0);
                }
            }
            if (this.CusGender != null)
            {
                if (this.CusGender.Length > 5)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CusGender", 5);
                }
                if (this.CusGender.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CusGender", 0);
                }
            }
            if (this.CusPhone != null)
            {
                if (this.CusPhone.Length > 15)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "CusPhone", 15);
                }
                if (this.CusPhone.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "CusPhone", 0);
                }
            }
            if (this.TblRoombook != null)
            {
                foreach (var element in this.TblRoombook)
                {
                    if (element != null)
                    {
                        element.Validate();
                    }
                }
            }
            if (this.TblServicesuse != null)
            {
                foreach (var element1 in this.TblServicesuse)
                {
                    if (element1 != null)
                    {
                        element1.Validate();
                    }
                }
            }
        }
    }
}
