// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HotelManager.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class TblServicesuse
    {
        /// <summary>
        /// Initializes a new instance of the TblServicesuse class.
        /// </summary>
        public TblServicesuse() { }

        /// <summary>
        /// Initializes a new instance of the TblServicesuse class.
        /// </summary>
        public TblServicesuse(string idCard, string idService, int? idServiceuse = default(int?), int? number = default(int?), DateTime? dateUse = default(DateTime?), TblCustomer tblCustomer = default(TblCustomer), TblServices tblServices = default(TblServices))
        {
            IdServiceuse = idServiceuse;
            IdCard = idCard;
            IdService = idService;
            Number = number;
            DateUse = dateUse;
            TblCustomer = tblCustomer;
            TblServices = tblServices;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idServiceuse")]
        public int? IdServiceuse { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idCard")]
        public string IdCard { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "idService")]
        public string IdService { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "number")]
        public int? Number { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateUse")]
        public DateTime? DateUse { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tbl_customer")]
        public TblCustomer TblCustomer { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tbl_services")]
        public TblServices TblServices { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (IdCard == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "IdCard");
            }
            if (IdService == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "IdService");
            }
            if (this.IdCard != null)
            {
                if (this.IdCard.Length > 12)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "IdCard", 12);
                }
                if (this.IdCard.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "IdCard", 0);
                }
            }
            if (this.IdService != null)
            {
                if (this.IdService.Length > 10)
                {
                    throw new ValidationException(ValidationRules.MaxLength, "IdService", 10);
                }
                if (this.IdService.Length < 0)
                {
                    throw new ValidationException(ValidationRules.MinLength, "IdService", 0);
                }
            }
            if (this.TblCustomer != null)
            {
                this.TblCustomer.Validate();
            }
            if (this.TblServices != null)
            {
                this.TblServices.Validate();
            }
        }
    }
}
