// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HotelManager
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for Room.
    /// </summary>
    public static partial class RoomExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<TblRoom> VGettbl(this IRoom operations)
            {
                return Task.Factory.StartNew(s => ((IRoom)s).VGettblAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<TblRoom>> VGettblAsync(this IRoom operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.VGettblWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tblRoom'>
            /// </param>
            public static TblRoom Posttbl(this IRoom operations, TblRoom tblRoom)
            {
                return Task.Factory.StartNew(s => ((IRoom)s).PosttblAsync(tblRoom), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tblRoom'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<TblRoom> PosttblAsync(this IRoom operations, TblRoom tblRoom, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PosttblWithHttpMessagesAsync(tblRoom, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            public static TblRoom Gettbl(this IRoom operations, string id)
            {
                return Task.Factory.StartNew(s => ((IRoom)s).GettblAsync(id), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<TblRoom> GettblAsync(this IRoom operations, string id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GettblWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='tblRoom'>
            /// </param>
            public static void Puttbl(this IRoom operations, string id, TblRoom tblRoom)
            {
                Task.Factory.StartNew(s => ((IRoom)s).PuttblAsync(id, tblRoom), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='tblRoom'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PuttblAsync(this IRoom operations, string id, TblRoom tblRoom, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.PuttblWithHttpMessagesAsync(id, tblRoom, null, cancellationToken).ConfigureAwait(false);
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            public static TblRoom Deletetbl(this IRoom operations, string id)
            {
                return Task.Factory.StartNew(s => ((IRoom)s).DeletetblAsync(id), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<TblRoom> DeletetblAsync(this IRoom operations, string id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DeletetblWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
