// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace HotelManager
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for Services.
    /// </summary>
    public static partial class ServicesExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static IList<TblServices> VGettbl(this IServices operations)
            {
                return Task.Factory.StartNew(s => ((IServices)s).VGettblAsync(), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<TblServices>> VGettblAsync(this IServices operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.VGettblWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tblServices'>
            /// </param>
            public static TblServices Posttbl(this IServices operations, TblServices tblServices)
            {
                return Task.Factory.StartNew(s => ((IServices)s).PosttblAsync(tblServices), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='tblServices'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<TblServices> PosttblAsync(this IServices operations, TblServices tblServices, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.PosttblWithHttpMessagesAsync(tblServices, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            public static TblServices Gettbl(this IServices operations, string id)
            {
                return Task.Factory.StartNew(s => ((IServices)s).GettblAsync(id), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<TblServices> GettblAsync(this IServices operations, string id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GettblWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='tblServices'>
            /// </param>
            public static void Puttbl(this IServices operations, string id, TblServices tblServices)
            {
                Task.Factory.StartNew(s => ((IServices)s).PuttblAsync(id, tblServices), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='tblServices'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PuttblAsync(this IServices operations, string id, TblServices tblServices, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.PuttblWithHttpMessagesAsync(id, tblServices, null, cancellationToken).ConfigureAwait(false);
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            public static TblServices Deletetbl(this IServices operations, string id)
            {
                return Task.Factory.StartNew(s => ((IServices)s).DeletetblAsync(id), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<TblServices> DeletetblAsync(this IServices operations, string id, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.DeletetblWithHttpMessagesAsync(id, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
